export const ELEMENTS = {
    signupBtn: '[data-qa="signup-button"]',
    signupNameInput: '[data-qa="signup-name"]',
    signupEmailInput: '[data-qa="signup-email"]',
    genderRadio: '#id_gender1',
    nameInput: '#name',
    passwordInput: '#password',
    daySelect: '#days',
    monthSelect: '#months',
    yearSelect: '#years',
    firstNameInput: '#first_name',
    lastNameInput: '#last_name',
    companyInput: '#company',
    adress1Input: '#address1',
    adress2Input: '#address2',
    countrySelect: '#country',
    stateInput: '#state',
    cityInput: '#city',
    zipcodeInput: '#zipcode',
    mobileNumberInput: '#mobile_number'
}